// <auto-generated />
using BazaSmakuAPI.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Base_of_Taste.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200531171557_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("BazaSmakuAPI.Models.Alergen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("ID");

                    b.ToTable("Alergen");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.AlergenDoSkladnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Alergen_ID");

                    b.Property<int>("Skladnik_ID");

                    b.HasKey("ID");

                    b.ToTable("AlergenDoSkladnik");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.Dieta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.Property<string>("Opis");

                    b.HasKey("ID");

                    b.ToTable("Dieta");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.Jednostka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.Property<string>("Skrot");

                    b.HasKey("ID");

                    b.ToTable("Jednostka");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.Opis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Przygotowanie");

                    b.Property<int>("Trudnosc");

                    b.Property<string>("opis");

                    b.HasKey("ID");

                    b.ToTable("Opis");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.Przepis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.Property<int>("Opis_ID");

                    b.HasKey("ID");

                    b.ToTable("Przepis");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.PrzepisDoDieta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Dieta_ID");

                    b.Property<int>("Przepis_ID");

                    b.HasKey("ID");

                    b.ToTable("PrzepisDoDieta");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.Skladnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("ID");

                    b.ToTable("Skladnik");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.SkladnikDoPrzepis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ilosc");

                    b.Property<string>("Jednostka_ID");

                    b.Property<int>("Przepis_ID");

                    b.Property<int>("Skladnik_ID");

                    b.HasKey("ID");

                    b.ToTable("SkladnikDoPrzepis");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.TypDania", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("ID");

                    b.ToTable("TypDania");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.TypDoPrzepis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Przepis_ID");

                    b.Property<int>("Typ_ID");

                    b.HasKey("ID");

                    b.ToTable("TypDoPrzepis");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.WartoscOdzywcza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("ID");

                    b.ToTable("WartoscOdzywcza");
                });

            modelBuilder.Entity("BazaSmakuAPI.Models.WartosciDoSkladnikow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ilosc");

                    b.Property<int>("Skladnik_ID");

                    b.Property<int>("Wartosc_ID");

                    b.HasKey("ID");

                    b.ToTable("WartosciDoSkladnikow");
                });
#pragma warning restore 612, 618
        }
    }
}
